//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameAnywhere.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameAnywhere.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrowDownload {
            get {
                object obj = ResourceManager.GetObject("arrowDownload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrowUpload {
            get {
                object obj = ResourceManager.GetObject("arrowUpload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backGameChoicePopupButton {
            get {
                object obj = ResourceManager.GetObject("backGameChoicePopupButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backGameChoicePopupButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("backGameChoicePopupButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backGameChoicePopupButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("backGameChoicePopupButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerChangePasswordPanel {
            get {
                object obj = ResourceManager.GetObject("bannerChangePasswordPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerChooseGamesToSync {
            get {
                object obj = ResourceManager.GetObject("bannerChooseGamesToSync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerConfirmGamesToSync {
            get {
                object obj = ResourceManager.GetObject("bannerConfirmGamesToSync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerConflictResolve {
            get {
                object obj = ResourceManager.GetObject("bannerConflictResolve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerForgetPasswordPanel {
            get {
                object obj = ResourceManager.GetObject("bannerForgetPasswordPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerLoginPanel {
            get {
                object obj = ResourceManager.GetObject("bannerLoginPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerRegisterPanel {
            get {
                object obj = ResourceManager.GetObject("bannerRegisterPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerResendActivationPanel {
            get {
                object obj = ResourceManager.GetObject("bannerResendActivationPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerSyncErrors {
            get {
                object obj = ResourceManager.GetObject("bannerSyncErrors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bannerSyncResults {
            get {
                object obj = ResourceManager.GetObject("bannerSyncResults", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonThumbdriveToComputer {
            get {
                object obj = ResourceManager.GetObject("buttonThumbdriveToComputer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonThumbdriveToComputerMouseOver {
            get {
                object obj = ResourceManager.GetObject("buttonThumbdriveToComputerMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancelLoginPanelButton {
            get {
                object obj = ResourceManager.GetObject("cancelLoginPanelButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancelLoginPanelButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("cancelLoginPanelButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancelLoginPanelButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("cancelLoginPanelButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap changePasswordPanelBackground {
            get {
                object obj = ResourceManager.GetObject("changePasswordPanelBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computerToThumbdriveButton {
            get {
                object obj = ResourceManager.GetObject("computerToThumbdriveButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computerToThumbdriveButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("computerToThumbdriveButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computerToThumbdriveButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("computerToThumbdriveButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computerToWebButton {
            get {
                object obj = ResourceManager.GetObject("computerToWebButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computerToWebButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("computerToWebButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computerToWebButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("computerToWebButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap confirmGameChoicePopupButton {
            get {
                object obj = ResourceManager.GetObject("confirmGameChoicePopupButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap confirmGameChoicePopupButtonDulled {
            get {
                object obj = ResourceManager.GetObject("confirmGameChoicePopupButtonDulled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap confirmGameChoicePopupButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("confirmGameChoicePopupButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap confirmGameChoicePopupButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("confirmGameChoicePopupButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doneResultPanelButton {
            get {
                object obj = ResourceManager.GetObject("doneResultPanelButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doneResultPanelButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("doneResultPanelButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doneResultPanelButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("doneResultPanelButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap downloadArrowed {
            get {
                object obj = ResourceManager.GetObject("downloadArrowed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap errorsButton {
            get {
                object obj = ResourceManager.GetObject("errorsButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap errorsButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("errorsButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap errorsButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("errorsButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exitButton {
            get {
                object obj = ResourceManager.GetObject("exitButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exitButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("exitButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exitButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("exitButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fifa2010 {
            get {
                object obj = ResourceManager.GetObject("fifa2010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap footballManagerIcon1 {
            get {
                object obj = ResourceManager.GetObject("footballManagerIcon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forgetPasswordPanelBackground {
            get {
                object obj = ResourceManager.GetObject("forgetPasswordPanelBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GameChoicePopupBackground {
            get {
                object obj = ResourceManager.GetObject("GameChoicePopupBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageWarning {
            get {
                object obj = ResourceManager.GetObject("imageWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loginButton {
            get {
                object obj = ResourceManager.GetObject("loginButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loginButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("loginButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loginButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("loginButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loginPanelBackground {
            get {
                object obj = ResourceManager.GetObject("loginPanelBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overallbackground2 {
            get {
                object obj = ResourceManager.GetObject("overallbackground2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overallbackground3 {
            get {
                object obj = ResourceManager.GetObject("overallbackground3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overallbackground4 {
            get {
                object obj = ResourceManager.GetObject("overallbackground4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap registerButton {
            get {
                object obj = ResourceManager.GetObject("registerButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap registerButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("registerButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap registerButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("registerButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap registerPanelBackground {
            get {
                object obj = ResourceManager.GetObject("registerPanelBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resendActivationPanelBackground {
            get {
                object obj = ResourceManager.GetObject("resendActivationPanelBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resendButton {
            get {
                object obj = ResourceManager.GetObject("resendButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resendButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("resendButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resendButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("resendButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sendButton {
            get {
                object obj = ResourceManager.GetObject("sendButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sendButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("sendButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sendButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("sendButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbdriveAndWebButton {
            get {
                object obj = ResourceManager.GetObject("thumbdriveAndWebButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbdriveAndWebButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("thumbdriveAndWebButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbdriveAndWebButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("thumbdriveAndWebButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbdriveToComputerButton {
            get {
                object obj = ResourceManager.GetObject("thumbdriveToComputerButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbdriveToComputerButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("thumbdriveToComputerButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumbdriveToComputerButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("thumbdriveToComputerButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload {
            get {
                object obj = ResourceManager.GetObject("upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uploadArrowed {
            get {
                object obj = ResourceManager.GetObject("uploadArrowed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warcraft3 {
            get {
                object obj = ResourceManager.GetObject("warcraft3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webToComputerButton {
            get {
                object obj = ResourceManager.GetObject("webToComputerButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webToComputerButtonMouseDown {
            get {
                object obj = ResourceManager.GetObject("webToComputerButtonMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webToComputerButtonMouseOver {
            get {
                object obj = ResourceManager.GetObject("webToComputerButtonMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap worldOfWarcraftIcon1 {
            get {
                object obj = ResourceManager.GetObject("worldOfWarcraftIcon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
